# Generated by Django 4.2.7 on 2023-11-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=255)),
                ('direcname', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
