# Generated by Django 4.2.7 on 2023-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default='default_poster.jpg', upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
